"""initial

Revision ID: 9054160ad76c
Revises: 
Create Date: 2026-06-30 10:55:46.094034

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9054160ad76c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('path', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('experiments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('git_commit', sa.String(length=40), nullable=True),
    sa.Column('branch', sa.String(length=255), nullable=True),
    sa.Column('repository_name', sa.String(length=255), nullable=True),
    sa.Column('tool', sa.String(length=50), nullable=False),
    sa.Column('tool_version', sa.String(length=50), nullable=True),
    sa.Column('device', sa.String(length=100), nullable=True),
    sa.Column('seed', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('compile_options', sa.JSON(), nullable=True),
    sa.Column('machine_info', sa.JSON(), nullable=True),
    sa.Column('changed_files', sa.JSON(), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_experiments_branch', 'experiments', ['branch'], unique=False)
    op.create_index('idx_experiments_device', 'experiments', ['device'], unique=False)
    op.create_index('idx_experiments_git_commit', 'experiments', ['git_commit'], unique=False)
    op.create_index('idx_experiments_project', 'experiments', ['project_id'], unique=False)
    op.create_index('idx_experiments_seed', 'experiments', ['seed'], unique=False)
    op.create_index('idx_experiments_status', 'experiments', ['status'], unique=False)
    op.create_index('idx_experiments_tool', 'experiments', ['tool'], unique=False)
    op.create_table('model_metadata',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('model_type', sa.String(length=50), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=False),
    sa.Column('dataset_size', sa.Integer(), nullable=True),
    sa.Column('accuracy', sa.Float(), nullable=True),
    sa.Column('training_duration', sa.Float(), nullable=True),
    sa.Column('trained_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('hyperparams', sa.JSON(), nullable=True),
    sa.Column('data_source', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('artifacts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('experiment_id', sa.Uuid(), nullable=False),
    sa.Column('path', sa.Text(), nullable=False),
    sa.Column('artifact_type', sa.String(length=50), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('checksum', sa.String(length=64), nullable=True),
    sa.Column('modification_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_artifacts_experiment', 'artifacts', ['experiment_id'], unique=False)
    op.create_table('recommendations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('experiment_id', sa.Uuid(), nullable=False),
    sa.Column('rule_name', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_recommendations_experiment', 'recommendations', ['experiment_id'], unique=False)
    op.create_table('reports',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('experiment_id', sa.Uuid(), nullable=False),
    sa.Column('report_type', sa.String(length=20), nullable=False),
    sa.Column('wns', sa.Float(), nullable=True),
    sa.Column('tns', sa.Float(), nullable=True),
    sa.Column('failing_paths', sa.Integer(), nullable=True),
    sa.Column('critical_path', sa.Text(), nullable=True),
    sa.Column('lut', sa.Integer(), nullable=True),
    sa.Column('lut_available', sa.Integer(), nullable=True),
    sa.Column('ff', sa.Integer(), nullable=True),
    sa.Column('ff_available', sa.Integer(), nullable=True),
    sa.Column('bram', sa.Integer(), nullable=True),
    sa.Column('bram_available', sa.Integer(), nullable=True),
    sa.Column('dsp', sa.Integer(), nullable=True),
    sa.Column('dsp_available', sa.Integer(), nullable=True),
    sa.Column('io_used', sa.Integer(), nullable=True),
    sa.Column('io_available', sa.Integer(), nullable=True),
    sa.Column('clock_utilization', sa.Float(), nullable=True),
    sa.Column('synthesis_duration', sa.Float(), nullable=True),
    sa.Column('implementation_duration', sa.Float(), nullable=True),
    sa.Column('bitstream_duration', sa.Float(), nullable=True),
    sa.Column('total_runtime', sa.Float(), nullable=True),
    sa.Column('raw_content', sa.Text(), nullable=True),
    sa.Column('source_file', sa.Text(), nullable=True),
    sa.Column('parsed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_reports_experiment', 'reports', ['experiment_id'], unique=False)
    op.create_index('idx_reports_type', 'reports', ['report_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_reports_type', table_name='reports')
    op.drop_index('idx_reports_experiment', table_name='reports')
    op.drop_table('reports')
    op.drop_index('idx_recommendations_experiment', table_name='recommendations')
    op.drop_table('recommendations')
    op.drop_index('idx_artifacts_experiment', table_name='artifacts')
    op.drop_table('artifacts')
    op.drop_table('model_metadata')
    op.drop_index('idx_experiments_tool', table_name='experiments')
    op.drop_index('idx_experiments_status', table_name='experiments')
    op.drop_index('idx_experiments_seed', table_name='experiments')
    op.drop_index('idx_experiments_project', table_name='experiments')
    op.drop_index('idx_experiments_git_commit', table_name='experiments')
    op.drop_index('idx_experiments_device', table_name='experiments')
    op.drop_index('idx_experiments_branch', table_name='experiments')
    op.drop_table('experiments')
    op.drop_table('projects')
    # ### end Alembic commands ###
